---
deployment:
  tasks:
    - export DEPLOYPATH=/home/yourusername/public_html
    - /bin/cp -R $REPOSITORY/* $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type d -exec /bin/chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec /bin/chmod 644 {} \;
    - /bin/chown -R yourusername:yourusername $DEPLOYPATH
