---
deploy:
  tasks:
    - export DEPLOYPATH=/home/ajcehosting/public_html
    - /bin/cp -R * $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type d -exec /bin/chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec /bin/chmod 644 {} \;
    - /bin/chown -R ajcehosting:ajcehosting $DEPLOYPATH
